version: "3.8"
services:
  app:
    build: ./siteblog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./siteblog/:/usr/src/siteblog/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    entrypoint: /usr/src/siteblog/entrypoint.sh
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  celery:
    build: ./siteblog
    command: celery -A siteblog worker -l info
    volumes:
      - ./siteblog/:/usr/src/siteblog/
    env_file:
      - ./.env.dev
    depends_on:
      - app
      - redis
      - db
  celery-beat:
    build: ./siteblog
    command: celery -A siteblog beat -l info
    volumes:
      - ./siteblog/:/usr/src/siteblog/
    env_file:
      - ./.env.dev
    depends_on:
      - celery
  flower:
    build: ./siteblog
    command: flower -A siteblog --port=5555
    volumes:
      - ./siteblog/:/usr/src/siteblog/
    env_file:
      - ./.env.dev
    ports:
      - 5555:5555
    depends_on:
      - celery
  redis:
    image: redis:alpine
    ports:
    - 6379:6379

volumes:
  postgres_data: