version: "3.8"
services:
  app:
    build: ./siteblog
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./siteblog/:/usr/src/siteblog/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev