# Generated by Django 3.1.4 on 2021-02-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210211_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
