# Generated by Django 3.1.4 on 2021-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mainslider_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='Fixed'),
        ),
    ]
