# Generated by Django 3.1.4 on 2021-03-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210322_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsubscriptions',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
